### ISSUE TITLE
scAtlas ontology lacks 'part of' (and all other object properties)

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/scatlas_ontology#13]
We need 'part of' relationships for the one of the main use-case for this ontology: grouping annotations by to anatomy and cell type terms by the anatomical structures they are part of.

Should be fixable by adding 'part of' (BFO_0000050) to the seed.

**Comment by dosumis** [comment]
Looks like this is set here:
https://github.com/EBISPOT/scatlas_ontology/blob/master/src/curation/scatlas_relations.txt (has BFO 50)

I suspect the problem is a typo here: https://github.com/EBISPOT/scatlas_ontology/blob/master/src/ontology/scatlas.Makefile#L59
SCATLAS_RELATIONS are removed not the [blacklist](https://github.com/EBISPOT/scatlas_ontology/blob/master/src/curation/blacklist.txt)

**Comment by matentzn** [comment]
Almost - the problem happened though in the second remove statement:

https://github.com/EBISPOT/scatlas_ontology/pull/14

Weird that it worked before - must have been during an unstable time of ROBOT remove..

**Comment by dosumis** [comment]
Thanks.  Looking back I can see the clause I flagged removed the complement.
