### ISSUE TITLE
EFO version in the component

### ISSUE THREAD

**Issue by pmb59** [EBISPOT/scatlas_ontology#36]
Could the EFO version be included in `./src/ontology/components/efo.owl`

We need to report this for SCXA releases , e.g. current is EFO 3.10.0
 http://www.ebi.ac.uk/gxa/sc/

**Comment by anitacaron** [comment]
Issue #35 will solve this too.

**Comment by anitacaron** [comment]
After updating to ODK 1.4, we can find the version in the EFO component.
